### ISSUE TITLE
Needs to be recompiled for Vaadin 8.2.x

### ISSUE THREAD

**Issue by amagnolo** [mstahv/cdi-helpers#9]
ViewMenuUI.handleNavigationError() doesn't work with Vaadin 8.2.1:
```
java.lang.NoSuchMethodError: com.vaadin.ui.Notification.show(Ljava/lang/String;Lcom/vaadin/ui/Notification$Type;)V
	at org.vaadin.cdiviewmenu.ViewMenuUI.handleNavigationError(ViewMenuUI.java:64)
```
The reason seems to be this:
"_Since Vaadin Framework 8.2.0 changed the signature of Notification.show, any dependency compiled with a version previous to 8.2.0 that uses the Notification.show method will break in client modules compiled with 8.2.0._" (https://vaadin.com/forum/#!/thread/16922205/16936080)

**Comment by amagnolo** [comment]
same thing for Vaadin Framework 8.3.0

**Comment by mstahv** [comment]
Hi, can you try with the latest version (2.3)? I hope this is now fixed. If not, get back to me with a project where this can be reproduced.

**Comment by amagnolo** [comment]
I confirm it's fixed in 2.3, thank you.

**Comment by mstahv** [comment]
Thanks!
